In [29]:
import pandas as pd
import urllib.request
from zipfile import ZipFile 

import csv
from csv import reader
from io import StringIO


import statistics 

from sqlalchemy import create_engine

import pprint

In [2]:
# to make an array of dates to generate url to match Citi Bike AWS files
month = list(["01", "02", "03","04","05","06","07","08","09","10","11","12"])
year = list(["2016","2017","2018"])

i=0 # iterates through the month list
j=0 # iterates through the year list

citi_bike_data = [] # to store each dataframe to be combined

In [3]:
for i in year:
    for j in month:
               
        try:  # Error Handling due to file name format inconsistencies
            
            # to create url
            url = (f"https://s3.amazonaws.com/tripdata/{i}{j}-citibike-tripdata.zip")
            
            
            #to use urlretriever to get the zip folder from Citi Bike Historical Data page
            filepath, header = urllib.request.urlretrieve(url)
            
            print(f"first try: {url}")
            
            # to assign csv name
            csv = (f"{i}{j}-citibike-tripdata.csv")
            
            with ZipFile(filepath, 'r') as zip:
                    #extract csv file
                    zip.printdir()
                    data = zip.read(csv)
            
            s=str(data,'utf-8')
            data = StringIO(s)
            df= pd.read_csv(data)
            
            #to convert data column headers to lowercase 
            df.columns = map(str.lower, df.columns)
            
            citi_bike_data.append(df)
            
            
            
            
        except:
            url = (f"https://s3.amazonaws.com/tripdata/{i}{j}-citibike-tripdata.csv.zip")
            
            filepath, header = urllib.request.urlretrieve(url)
           
            print(f"second try: {url}")
            
            
            # to assign csv name
            csv = (f"{i}{j}-citibike-tripdata.csv")
            
            with ZipFile(filepath, 'r') as zip:
                    #extract csv file
                    zip.printdir()
                    data = zip.read(csv)
            
            s=str(data,'utf-8')
            data = StringIO(s)
            df= pd.read_csv(data)
            
            #to convert data column headers to lowercase 
            df.columns = map(str.lower, df.columns)
            
            citi_bike_data.append(df)

first try: https://s3.amazonaws.com/tripdata/201601-citibike-tripdata.zip
File Name                                             Modified             Size
201601-citibike-tripdata.csv                   2016-02-03 09:55:32     98943693
first try: https://s3.amazonaws.com/tripdata/201602-citibike-tripdata.zip
File Name                                             Modified             Size
201602-citibike-tripdata.csv                   2016-03-01 14:47:34    109005808
first try: https://s3.amazonaws.com/tripdata/201603-citibike-tripdata.zip
File Name                                             Modified             Size
201603-citibike-tripdata.csv                   2016-04-21 14:49:04    179040936
first try: https://s3.amazonaws.com/tripdata/201604-citibike-tripdata.zip
File Name                                             Modified             Size
201604-citibike-tripdata.csv                   2016-06-01 11:26:52    197554966
first try: https://s3.amazonaws.com/tripdata/201605-citibike-tripdata.zip
File Name                                             Modified             Size
201605-citibike-tripdata.csv                   2016-06-01 11:27:34    236469340
first try: https://s3.amazonaws.com/tripdata/201606-citibike-tripdata.zip
File Name                                             Modified             Size
201606-citibike-tripdata.csv                   2016-07-12 12:26:38    285054310
first try: https://s3.amazonaws.com/tripdata/201607-citibike-tripdata.zip
File Name                                             Modified             Size
201607-citibike-tripdata.csv                   2016-10-04 12:20:44    270130948
first try: https://s3.amazonaws.com/tripdata/201608-citibike-tripdata.zip
File Name                                             Modified             Size
201608-citibike-tripdata.csv                   2016-10-04 12:21:20    305140326
first try: https://s3.amazonaws.com/tripdata/201609-citibike-tripdata.zip
File Name                                             Modified             Size
201609-citibike-tripdata.csv                   2016-10-04 12:19:16    323792655
first try: https://s3.amazonaws.com/tripdata/201610-citibike-tripdata.zip
File Name                                             Modified             Size
201610-citibike-tripdata.csv                   2017-01-20 15:44:52    265268579
first try: https://s3.amazonaws.com/tripdata/201611-citibike-tripdata.zip
File Name                                             Modified             Size
201611-citibike-tripdata.csv                   2017-01-20 15:48:32    201556405
first try: https://s3.amazonaws.com/tripdata/201612-citibike-tripdata.zip
File Name                                             Modified             Size
201612-citibike-tripdata.csv                   2017-01-20 15:51:08    136661429
second try: https://s3.amazonaws.com/tripdata/201701-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201701-citibike-tripdata.csv                   2017-04-06 15:27:34    122344055
second try: https://s3.amazonaws.com/tripdata/201702-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201702-citibike-tripdata.csv                   2017-04-06 15:30:02    133371742
second try: https://s3.amazonaws.com/tripdata/201703-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201703-citibike-tripdata.csv                   2017-04-06 15:32:26    122563390
second try: https://s3.amazonaws.com/tripdata/201704-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201704-citibike-tripdata.csv                   2017-08-01 11:49:36    234847839
second try: https://s3.amazonaws.com/tripdata/201705-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201705-citibike-tripdata.csv                   2017-08-01 12:07:36    272075738
second try: https://s3.amazonaws.com/tripdata/201706-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201706-citibike-tripdata.csv                   2017-08-01 12:10:54    309685933
second try: https://s3.amazonaws.com/tripdata/201707-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201707-citibike-tripdata.csv                   2017-08-01 12:14:56    310739897
second try: https://s3.amazonaws.com/tripdata/201708-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201708-citibike-tripdata.csv                   2017-10-03 11:44:18    325254486
second try: https://s3.amazonaws.com/tripdata/201709-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201709-citibike-tripdata.csv                   2017-10-03 11:47:40    336395375
second try: https://s3.amazonaws.com/tripdata/201710-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201710-citibike-tripdata.csv                   2018-01-31 16:12:18    340152955
second try: https://s3.amazonaws.com/tripdata/201711-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201711-citibike-tripdata.csv                   2018-01-31 16:09:08    238119094
second try: https://s3.amazonaws.com/tripdata/201712-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201712-citibike-tripdata.csv                   2018-01-31 16:06:48    159356525
second try: https://s3.amazonaws.com/tripdata/201801-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201801-citibike-tripdata.csv                   2018-09-06 11:13:04    135954660
second try: https://s3.amazonaws.com/tripdata/201802-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201802-citibike-tripdata.csv                   2018-09-06 13:34:28    159702866
second try: https://s3.amazonaws.com/tripdata/201803-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201803-citibike-tripdata.csv                   2018-09-06 13:26:26    185038803
second try: https://s3.amazonaws.com/tripdata/201804-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201804-citibike-tripdata.csv                   2018-09-06 11:58:00    248398688
second try: https://s3.amazonaws.com/tripdata/201805-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201805-citibike-tripdata.csv                   2018-09-06 11:52:08    346788777
second try: https://s3.amazonaws.com/tripdata/201806-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201806-citibike-tripdata.csv                   2018-09-06 11:44:56    371493210
second try: https://s3.amazonaws.com/tripdata/201807-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201807-citibike-tripdata.csv                   2018-09-06 11:36:36    364208046
second try: https://s3.amazonaws.com/tripdata/201808-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201808-citibike-tripdata.csv                   2018-09-12 14:49:00    376643964
second try: https://s3.amazonaws.com/tripdata/201809-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201809-citibike-tripdata.csv                   2018-10-03 14:45:14    357819814
second try: https://s3.amazonaws.com/tripdata/201810-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201810-citibike-tripdata.csv                   2018-11-07 14:02:36    357616248
second try: https://s3.amazonaws.com/tripdata/201811-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201811-citibike-tripdata.csv                   2018-12-04 10:40:32    239642680

second try: https://s3.amazonaws.com/tripdata/201812-citibike-tripdata.csv.zip
File Name                                             Modified             Size
201812-citibike-tripdata.csv                   2019-01-08 13:27:18    193411177

In [4]:
len_of_df = len(citi_bike_data)
print(f"# of df {len_of_df}")

list_of_headers = []
list_of_columns = []

i=0

while i < len_of_df: 
    
    # to calculate the number of headers for datasets
    headers = citi_bike_data[i].columns
    # to get the value of the number of headers for datasets
    num_headers = len(headers)
    
    # to create a list of header values to evaulate what is the mode
    list_of_headers.append(headers)
    list_of_columns.append(num_headers)
       
    i += 1

print(f"dataframe header reviewed")



# to observe the number of headers vs the mode 
## if any datasets have a number of headers that do not equal the mode then the datasets
## will have an issue appeneding in the PostgreSQL database 
mode_headers = statistics.mode(list_of_columns)

variance = list(set(list_of_columns))

if mode_headers == variance[0]:
    print('same number of columns')

# of df 36
dataframe header reviewed
same number of columns

In [26]:
# to review the column headers
## if a column header text is changed it will affect the import of the data into PostgreSQl

column_headers = {}

i=0 #iterate through dataframes
j=0 # iterate through columns 
k= i + i #to enumerate the amount of times the value occured in the dataframes


for i in range(len_of_df):
    for j in range(variance[0]):
        column_headers.update({
            list_of_headers[i][j]: (i+i)
            })
    
        print(f"Completed DataFrame {i} for column {j}")

Completed DataFrame 0 for column 0
Completed DataFrame 0 for column 1
Completed DataFrame 0 for column 2
Completed DataFrame 0 for column 3
Completed DataFrame 0 for column 4
Completed DataFrame 0 for column 5
Completed DataFrame 0 for column 6
Completed DataFrame 0 for column 7
Completed DataFrame 0 for column 8
Completed DataFrame 0 for column 9
Completed DataFrame 0 for column 10
Completed DataFrame 0 for column 11
Completed DataFrame 0 for column 12
Completed DataFrame 0 for column 13
Completed DataFrame 0 for column 14
Completed DataFrame 1 for column 0
Completed DataFrame 1 for column 1
Completed DataFrame 1 for column 2
Completed DataFrame 1 for column 3
Completed DataFrame 1 for column 4
Completed DataFrame 1 for column 5
Completed DataFrame 1 for column 6
Completed DataFrame 1 for column 7
Completed DataFrame 1 for column 8
Completed DataFrame 1 for column 9
Completed DataFrame 1 for column 10
Completed DataFrame 1 for column 11
Completed DataFrame 1 for column 12
Completed DataFrame 1 for column 13
Completed DataFrame 1 for column 14
Completed DataFrame 2 for column 0
Completed DataFrame 2 for column 1
Completed DataFrame 2 for column 2
Completed DataFrame 2 for column 3
Completed DataFrame 2 for column 4
Completed DataFrame 2 for column 5
Completed DataFrame 2 for column 6
Completed DataFrame 2 for column 7
Completed DataFrame 2 for column 8
Completed DataFrame 2 for column 9
Completed DataFrame 2 for column 10
Completed DataFrame 2 for column 11
Completed DataFrame 2 for column 12
Completed DataFrame 2 for column 13
Completed DataFrame 2 for column 14
Completed DataFrame 3 for column 0
Completed DataFrame 3 for column 1
Completed DataFrame 3 for column 2
Completed DataFrame 3 for column 3
Completed DataFrame 3 for column 4
Completed DataFrame 3 for column 5
Completed DataFrame 3 for column 6
Completed DataFrame 3 for column 7
Completed DataFrame 3 for column 8
Completed DataFrame 3 for column 9
Completed DataFrame 3 for column 10
Completed DataFrame 3 for column 11
Completed DataFrame 3 for column 12
Completed DataFrame 3 for column 13
Completed DataFrame 3 for column 14
Completed DataFrame 4 for column 0
Completed DataFrame 4 for column 1
Completed DataFrame 4 for column 2
Completed DataFrame 4 for column 3
Completed DataFrame 4 for column 4
Completed DataFrame 4 for column 5
Completed DataFrame 4 for column 6
Completed DataFrame 4 for column 7
Completed DataFrame 4 for column 8
Completed DataFrame 4 for column 9
Completed DataFrame 4 for column 10
Completed DataFrame 4 for column 11
Completed DataFrame 4 for column 12
Completed DataFrame 4 for column 13
Completed DataFrame 4 for column 14
Completed DataFrame 5 for column 0
Completed DataFrame 5 for column 1
Completed DataFrame 5 for column 2
Completed DataFrame 5 for column 3
Completed DataFrame 5 for column 4
Completed DataFrame 5 for column 5
Completed DataFrame 5 for column 6
Completed DataFrame 5 for column 7
Completed DataFrame 5 for column 8
Completed DataFrame 5 for column 9
Completed DataFrame 5 for column 10
Completed DataFrame 5 for column 11
Completed DataFrame 5 for column 12
Completed DataFrame 5 for column 13
Completed DataFrame 5 for column 14
Completed DataFrame 6 for column 0
Completed DataFrame 6 for column 1
Completed DataFrame 6 for column 2
Completed DataFrame 6 for column 3
Completed DataFrame 6 for column 4
Completed DataFrame 6 for column 5
Completed DataFrame 6 for column 6
Completed DataFrame 6 for column 7
Completed DataFrame 6 for column 8
Completed DataFrame 6 for column 9
Completed DataFrame 6 for column 10
Completed DataFrame 6 for column 11
Completed DataFrame 6 for column 12
Completed DataFrame 6 for column 13
Completed DataFrame 6 for column 14
Completed DataFrame 7 for column 0
Completed DataFrame 7 for column 1
Completed DataFrame 7 for column 2
Completed DataFrame 7 for column 3
Completed DataFrame 7 for column 4
Completed DataFrame 7 for column 5
Completed DataFrame 7 for column 6
Completed DataFrame 7 for column 7
Completed DataFrame 7 for column 8
Completed DataFrame 7 for column 9
Completed DataFrame 7 for column 10
Completed DataFrame 7 for column 11
Completed DataFrame 7 for column 12
Completed DataFrame 7 for column 13
Completed DataFrame 7 for column 14
Completed DataFrame 8 for column 0
Completed DataFrame 8 for column 1
Completed DataFrame 8 for column 2
Completed DataFrame 8 for column 3
Completed DataFrame 8 for column 4
Completed DataFrame 8 for column 5
Completed DataFrame 8 for column 6
Completed DataFrame 8 for column 7
Completed DataFrame 8 for column 8
Completed DataFrame 8 for column 9
Completed DataFrame 8 for column 10
Completed DataFrame 8 for column 11
Completed DataFrame 8 for column 12
Completed DataFrame 8 for column 13
Completed DataFrame 8 for column 14
Completed DataFrame 9 for column 0
Completed DataFrame 9 for column 1
Completed DataFrame 9 for column 2
Completed DataFrame 9 for column 3
Completed DataFrame 9 for column 4
Completed DataFrame 9 for column 5
Completed DataFrame 9 for column 6
Completed DataFrame 9 for column 7
Completed DataFrame 9 for column 8
Completed DataFrame 9 for column 9
Completed DataFrame 9 for column 10
Completed DataFrame 9 for column 11
Completed DataFrame 9 for column 12
Completed DataFrame 9 for column 13
Completed DataFrame 9 for column 14
Completed DataFrame 10 for column 0
Completed DataFrame 10 for column 1
Completed DataFrame 10 for column 2
Completed DataFrame 10 for column 3
Completed DataFrame 10 for column 4
Completed DataFrame 10 for column 5
Completed DataFrame 10 for column 6
Completed DataFrame 10 for column 7
Completed DataFrame 10 for column 8
Completed DataFrame 10 for column 9
Completed DataFrame 10 for column 10
Completed DataFrame 10 for column 11
Completed DataFrame 10 for column 12
Completed DataFrame 10 for column 13
Completed DataFrame 10 for column 14
Completed DataFrame 11 for column 0
Completed DataFrame 11 for column 1
Completed DataFrame 11 for column 2
Completed DataFrame 11 for column 3
Completed DataFrame 11 for column 4
Completed DataFrame 11 for column 5
Completed DataFrame 11 for column 6
Completed DataFrame 11 for column 7
Completed DataFrame 11 for column 8
Completed DataFrame 11 for column 9
Completed DataFrame 11 for column 10
Completed DataFrame 11 for column 11
Completed DataFrame 11 for column 12
Completed DataFrame 11 for column 13
Completed DataFrame 11 for column 14
Completed DataFrame 12 for column 0
Completed DataFrame 12 for column 1
Completed DataFrame 12 for column 2
Completed DataFrame 12 for column 3
Completed DataFrame 12 for column 4
Completed DataFrame 12 for column 5
Completed DataFrame 12 for column 6
Completed DataFrame 12 for column 7
Completed DataFrame 12 for column 8
Completed DataFrame 12 for column 9
Completed DataFrame 12 for column 10
Completed DataFrame 12 for column 11
Completed DataFrame 12 for column 12
Completed DataFrame 12 for column 13
Completed DataFrame 12 for column 14
Completed DataFrame 13 for column 0
Completed DataFrame 13 for column 1
Completed DataFrame 13 for column 2
Completed DataFrame 13 for column 3
Completed DataFrame 13 for column 4
Completed DataFrame 13 for column 5
Completed DataFrame 13 for column 6
Completed DataFrame 13 for column 7
Completed DataFrame 13 for column 8
Completed DataFrame 13 for column 9
Completed DataFrame 13 for column 10
Completed DataFrame 13 for column 11
Completed DataFrame 13 for column 12
Completed DataFrame 13 for column 13
Completed DataFrame 13 for column 14
Completed DataFrame 14 for column 0
Completed DataFrame 14 for column 1
Completed DataFrame 14 for column 2
Completed DataFrame 14 for column 3
Completed DataFrame 14 for column 4
Completed DataFrame 14 for column 5
Completed DataFrame 14 for column 6
Completed DataFrame 14 for column 7
Completed DataFrame 14 for column 8
Completed DataFrame 14 for column 9
Completed DataFrame 14 for column 10
Completed DataFrame 14 for column 11
Completed DataFrame 14 for column 12
Completed DataFrame 14 for column 13
Completed DataFrame 14 for column 14
Completed DataFrame 15 for column 0
Completed DataFrame 15 for column 1
Completed DataFrame 15 for column 2
Completed DataFrame 15 for column 3
Completed DataFrame 15 for column 4
Completed DataFrame 15 for column 5
Completed DataFrame 15 for column 6
Completed DataFrame 15 for column 7
Completed DataFrame 15 for column 8
Completed DataFrame 15 for column 9
Completed DataFrame 15 for column 10
Completed DataFrame 15 for column 11
Completed DataFrame 15 for column 12
Completed DataFrame 15 for column 13
Completed DataFrame 15 for column 14
Completed DataFrame 16 for column 0
Completed DataFrame 16 for column 1
Completed DataFrame 16 for column 2
Completed DataFrame 16 for column 3
Completed DataFrame 16 for column 4
Completed DataFrame 16 for column 5
Completed DataFrame 16 for column 6
Completed DataFrame 16 for column 7
Completed DataFrame 16 for column 8
Completed DataFrame 16 for column 9
Completed DataFrame 16 for column 10
Completed DataFrame 16 for column 11
Completed DataFrame 16 for column 12
Completed DataFrame 16 for column 13
Completed DataFrame 16 for column 14
Completed DataFrame 17 for column 0
Completed DataFrame 17 for column 1
Completed DataFrame 17 for column 2
Completed DataFrame 17 for column 3
Completed DataFrame 17 for column 4
Completed DataFrame 17 for column 5
Completed DataFrame 17 for column 6
Completed DataFrame 17 for column 7
Completed DataFrame 17 for column 8
Completed DataFrame 17 for column 9
Completed DataFrame 17 for column 10
Completed DataFrame 17 for column 11
Completed DataFrame 17 for column 12
Completed DataFrame 17 for column 13
Completed DataFrame 17 for column 14
Completed DataFrame 18 for column 0
Completed DataFrame 18 for column 1
Completed DataFrame 18 for column 2
Completed DataFrame 18 for column 3
Completed DataFrame 18 for column 4
Completed DataFrame 18 for column 5
Completed DataFrame 18 for column 6
Completed DataFrame 18 for column 7
Completed DataFrame 18 for column 8
Completed DataFrame 18 for column 9
Completed DataFrame 18 for column 10
Completed DataFrame 18 for column 11
Completed DataFrame 18 for column 12
Completed DataFrame 18 for column 13
Completed DataFrame 18 for column 14
Completed DataFrame 19 for column 0
Completed DataFrame 19 for column 1
Completed DataFrame 19 for column 2
Completed DataFrame 19 for column 3
Completed DataFrame 19 for column 4
Completed DataFrame 19 for column 5
Completed DataFrame 19 for column 6
Completed DataFrame 19 for column 7
Completed DataFrame 19 for column 8
Completed DataFrame 19 for column 9
Completed DataFrame 19 for column 10
Completed DataFrame 19 for column 11
Completed DataFrame 19 for column 12
Completed DataFrame 19 for column 13
Completed DataFrame 19 for column 14
Completed DataFrame 20 for column 0
Completed DataFrame 20 for column 1
Completed DataFrame 20 for column 2
Completed DataFrame 20 for column 3
Completed DataFrame 20 for column 4
Completed DataFrame 20 for column 5
Completed DataFrame 20 for column 6
Completed DataFrame 20 for column 7
Completed DataFrame 20 for column 8
Completed DataFrame 20 for column 9
Completed DataFrame 20 for column 10
Completed DataFrame 20 for column 11
Completed DataFrame 20 for column 12
Completed DataFrame 20 for column 13
Completed DataFrame 20 for column 14
Completed DataFrame 21 for column 0
Completed DataFrame 21 for column 1
Completed DataFrame 21 for column 2
Completed DataFrame 21 for column 3
Completed DataFrame 21 for column 4
Completed DataFrame 21 for column 5
Completed DataFrame 21 for column 6
Completed DataFrame 21 for column 7
Completed DataFrame 21 for column 8
Completed DataFrame 21 for column 9
Completed DataFrame 21 for column 10
Completed DataFrame 21 for column 11
Completed DataFrame 21 for column 12
Completed DataFrame 21 for column 13
Completed DataFrame 21 for column 14
Completed DataFrame 22 for column 0
Completed DataFrame 22 for column 1
Completed DataFrame 22 for column 2
Completed DataFrame 22 for column 3
Completed DataFrame 22 for column 4
Completed DataFrame 22 for column 5
Completed DataFrame 22 for column 6
Completed DataFrame 22 for column 7
Completed DataFrame 22 for column 8
Completed DataFrame 22 for column 9
Completed DataFrame 22 for column 10
Completed DataFrame 22 for column 11
Completed DataFrame 22 for column 12
Completed DataFrame 22 for column 13
Completed DataFrame 22 for column 14
Completed DataFrame 23 for column 0
Completed DataFrame 23 for column 1
Completed DataFrame 23 for column 2
Completed DataFrame 23 for column 3
Completed DataFrame 23 for column 4
Completed DataFrame 23 for column 5
Completed DataFrame 23 for column 6
Completed DataFrame 23 for column 7
Completed DataFrame 23 for column 8
Completed DataFrame 23 for column 9
Completed DataFrame 23 for column 10
Completed DataFrame 23 for column 11
Completed DataFrame 23 for column 12
Completed DataFrame 23 for column 13
Completed DataFrame 23 for column 14
Completed DataFrame 24 for column 0
Completed DataFrame 24 for column 1
Completed DataFrame 24 for column 2
Completed DataFrame 24 for column 3
Completed DataFrame 24 for column 4
Completed DataFrame 24 for column 5
Completed DataFrame 24 for column 6
Completed DataFrame 24 for column 7
Completed DataFrame 24 for column 8
Completed DataFrame 24 for column 9
Completed DataFrame 24 for column 10
Completed DataFrame 24 for column 11
Completed DataFrame 24 for column 12
Completed DataFrame 24 for column 13
Completed DataFrame 24 for column 14
Completed DataFrame 25 for column 0
Completed DataFrame 25 for column 1
Completed DataFrame 25 for column 2
Completed DataFrame 25 for column 3
Completed DataFrame 25 for column 4
Completed DataFrame 25 for column 5
Completed DataFrame 25 for column 6
Completed DataFrame 25 for column 7
Completed DataFrame 25 for column 8
Completed DataFrame 25 for column 9
Completed DataFrame 25 for column 10
Completed DataFrame 25 for column 11
Completed DataFrame 25 for column 12
Completed DataFrame 25 for column 13
Completed DataFrame 25 for column 14
Completed DataFrame 26 for column 0
Completed DataFrame 26 for column 1
Completed DataFrame 26 for column 2
Completed DataFrame 26 for column 3
Completed DataFrame 26 for column 4
Completed DataFrame 26 for column 5
Completed DataFrame 26 for column 6
Completed DataFrame 26 for column 7
Completed DataFrame 26 for column 8
Completed DataFrame 26 for column 9
Completed DataFrame 26 for column 10
Completed DataFrame 26 for column 11
Completed DataFrame 26 for column 12
Completed DataFrame 26 for column 13
Completed DataFrame 26 for column 14
Completed DataFrame 27 for column 0
Completed DataFrame 27 for column 1
Completed DataFrame 27 for column 2
Completed DataFrame 27 for column 3
Completed DataFrame 27 for column 4
Completed DataFrame 27 for column 5
Completed DataFrame 27 for column 6
Completed DataFrame 27 for column 7
Completed DataFrame 27 for column 8
Completed DataFrame 27 for column 9
Completed DataFrame 27 for column 10
Completed DataFrame 27 for column 11
Completed DataFrame 27 for column 12
Completed DataFrame 27 for column 13
Completed DataFrame 27 for column 14
Completed DataFrame 28 for column 0
Completed DataFrame 28 for column 1
Completed DataFrame 28 for column 2
Completed DataFrame 28 for column 3
Completed DataFrame 28 for column 4
Completed DataFrame 28 for column 5
Completed DataFrame 28 for column 6
Completed DataFrame 28 for column 7
Completed DataFrame 28 for column 8
Completed DataFrame 28 for column 9
Completed DataFrame 28 for column 10
Completed DataFrame 28 for column 11
Completed DataFrame 28 for column 12
Completed DataFrame 28 for column 13
Completed DataFrame 28 for column 14
Completed DataFrame 29 for column 0
Completed DataFrame 29 for column 1
Completed DataFrame 29 for column 2
Completed DataFrame 29 for column 3
Completed DataFrame 29 for column 4
Completed DataFrame 29 for column 5
Completed DataFrame 29 for column 6
Completed DataFrame 29 for column 7
Completed DataFrame 29 for column 8
Completed DataFrame 29 for column 9
Completed DataFrame 29 for column 10
Completed DataFrame 29 for column 11
Completed DataFrame 29 for column 12
Completed DataFrame 29 for column 13
Completed DataFrame 29 for column 14
Completed DataFrame 30 for column 0
Completed DataFrame 30 for column 1
Completed DataFrame 30 for column 2
Completed DataFrame 30 for column 3
Completed DataFrame 30 for column 4
Completed DataFrame 30 for column 5
Completed DataFrame 30 for column 6
Completed DataFrame 30 for column 7
Completed DataFrame 30 for column 8
Completed DataFrame 30 for column 9
Completed DataFrame 30 for column 10
Completed DataFrame 30 for column 11
Completed DataFrame 30 for column 12
Completed DataFrame 30 for column 13
Completed DataFrame 30 for column 14
Completed DataFrame 31 for column 0
Completed DataFrame 31 for column 1
Completed DataFrame 31 for column 2
Completed DataFrame 31 for column 3
Completed DataFrame 31 for column 4
Completed DataFrame 31 for column 5
Completed DataFrame 31 for column 6
Completed DataFrame 31 for column 7
Completed DataFrame 31 for column 8
Completed DataFrame 31 for column 9
Completed DataFrame 31 for column 10
Completed DataFrame 31 for column 11
Completed DataFrame 31 for column 12
Completed DataFrame 31 for column 13
Completed DataFrame 31 for column 14
Completed DataFrame 32 for column 0
Completed DataFrame 32 for column 1
Completed DataFrame 32 for column 2
Completed DataFrame 32 for column 3
Completed DataFrame 32 for column 4
Completed DataFrame 32 for column 5
Completed DataFrame 32 for column 6
Completed DataFrame 32 for column 7
Completed DataFrame 32 for column 8
Completed DataFrame 32 for column 9
Completed DataFrame 32 for column 10
Completed DataFrame 32 for column 11
Completed DataFrame 32 for column 12
Completed DataFrame 32 for column 13
Completed DataFrame 32 for column 14
Completed DataFrame 33 for column 0
Completed DataFrame 33 for column 1
Completed DataFrame 33 for column 2
Completed DataFrame 33 for column 3
Completed DataFrame 33 for column 4
Completed DataFrame 33 for column 5
Completed DataFrame 33 for column 6
Completed DataFrame 33 for column 7
Completed DataFrame 33 for column 8
Completed DataFrame 33 for column 9
Completed DataFrame 33 for column 10
Completed DataFrame 33 for column 11
Completed DataFrame 33 for column 12
Completed DataFrame 33 for column 13
Completed DataFrame 33 for column 14
Completed DataFrame 34 for column 0
Completed DataFrame 34 for column 1
Completed DataFrame 34 for column 2
Completed DataFrame 34 for column 3
Completed DataFrame 34 for column 4
Completed DataFrame 34 for column 5
Completed DataFrame 34 for column 6
Completed DataFrame 34 for column 7
Completed DataFrame 34 for column 8
Completed DataFrame 34 for column 9
Completed DataFrame 34 for column 10
Completed DataFrame 34 for column 11
Completed DataFrame 34 for column 12
Completed DataFrame 34 for column 13
Completed DataFrame 34 for column 14
Completed DataFrame 35 for column 0
Completed DataFrame 35 for column 1
Completed DataFrame 35 for column 2
Completed DataFrame 35 for column 3
Completed DataFrame 35 for column 4
Completed DataFrame 35 for column 5
Completed DataFrame 35 for column 6
Completed DataFrame 35 for column 7
Completed DataFrame 35 for column 8
Completed DataFrame 35 for column 9
Completed DataFrame 35 for column 10
Completed DataFrame 35 for column 11
Completed DataFrame 35 for column 12
Completed DataFrame 35 for column 13
Completed DataFrame 35 for column 14

In [35]:
# to review the column headers and their frequency
sorted(column_headers.keys())
pprint.pprint(column_headers)

{'bike id': 28,
 'bikeid': 70,
 'birth year': 70,
 'end station id': 70,
 'end station latitude': 70,
 'end station longitude': 70,
 'end station name': 70,
 'gender': 70,
 'start station id': 70,
 'start station latitude': 70,
 'start station longitude': 70,
 'start station name': 70,
 'start time': 28,
 'starttime': 70,
 'stop time': 28,
 'stoptime': 70,
 'trip duration': 28,
 'tripduration': 70,
 'user type': 28,
 'usertype': 70}

In [49]:
## to review which columns do not match 

# the max value can also be assumed to be the mode of the keys occurance in the datasets
max_key = max(column_headers, key=column_headers.get)
max_value = column_headers[max_key]
print(max_value)

# filtering the dictionary by the max value to see which columns are new to the dataset
un_matched = {key: value for key, value in column_headers.items() if value < max_value}
print(un_matched)

# made a list of columns to rename 
rename_columns = list(un_matched.keys())

## output: ['trip duration', 'start time', 'stop time', 'bike id', 'user type']

print(rename_columns)

70
{'trip duration': 28, 'start time': 28, 'stop time': 28, 'bike id': 28, 'user type': 28}
['trip duration', 'start time', 'stop time', 'bike id', 'user type']

In [ ]:
# i = 0


# engine = create_engine ('postgresql://postgres:postgres@localhost:5432/citi_bike_data')

# while i <= len(citi_bike_data):
#     # to update a PostgreSQL table
#     citi_bike_data[i].to_sql('citi_bike_trip_history', engine, if_exists='append')
    
#     print(f"Completed {i} of citi_bike_data df")
#     i += 1

In [ ]:
# usefile sites
# ------------------------------------

# -- jupyter notebook --
# memory extension: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html

# -- data gathering --
# urllib request: https://stackoverflow.com/questions/34740288/importerror-no-module-named-urllib2-python-3
# zipfile: https://docs.python.org/2/library/zipfile.html
# zip file read: https://www.geeksforgeeks.org/working-zip-files-python/

# -- data manipulation --
# bytes to dataframe: https://stackoverflow.com/questions/47379476/how-to-convert-bytes-data-into-a-python-pandas-dataframe

# -- data cleaning & aggregation --
# error handling: https://stackoverflow.com/questions/2792568/running-code-if-try-statements-were-successful-in-python
# testing return val for error handling: https://stackoverflow.com/questions/19805654/python-try-finally-block-returns
# append dataframe to PostgreSQL table: https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.to_sql.html